---
port: 4000
host: 0.0.0.0
safe: false

### site serving configuration ###
exclude: [README.md, .gitignore]
timezone: null
lsi: false
markdown: kramdown


### content configuration ###
title:       "Workshop on Machine Reading for Question Answering (MRQA) 2018"
keywords:    "workshop, machine reading, question answering, reading comprehension"
description: "The official website for the 2018 Workshop on Machine Reading for Question Answering (MRQA2018)"
source_link: "https://github.com/mrqa2018/mrqa2018.github.io"
favicon:     #put a path like: "img/favicon.ico"
touch_icon:  #put a path like: "img/apple-touch-icon.png"
